name: 'Assign reviewers'
description: 'Assign configured users on review'
inputs:
  GITHUB_TOKEN:
    required: true
  who-to-assign:
    description: 'Usernames of people to assign (space-separated)'
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'index.js'